[tool.poetry]
name = "shellcar"
version = "0.0.0"
description = ""
authors = ["Luke Hodkinson <luke@expensecheck.com.au>"]

[tool.poetry.dependencies]
python = "^3.7"
flask = "^2.2.5"

[tool.poetry.dev-dependencies]
